trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallNginx
  displayName: 'Install Nginx'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y nginx
    displayName: 'Install Nginx'

  - script: sudo service nginx start
    displayName: 'Start Nginx'

